const collection = [
    {
        name: "Dune",
        author: "Frank Herbert",
        year: 1965,
        synopsis: "Dune is a science fiction epic that takes place on the desert planet of Arrakis, where the most valuable substance in the universe - melange - is mined. The novel follows the story of Paul Atreides, a young nobleman, as he navigates the complex political and ecological landscape of Dune, facing power struggles, environmental challenges, and the prophecy of a messiah.",
        adaptations: "Dune (movie) - 1984 / Dune (movie) - 2021",
        cover: "/images/dune.jpg",
    },
    {
        name: "The Word for World is Forest",
        author: "Ursula K Le Guin",
        year: 1972,
        synopsis: "In this novel, Ursula K. Le Guin explores themes of colonization and environmentalism. It's set on a distant planet called Athshe, where Earthlings exploit the native population and their lush forest, leading to a clash of cultures and a battle for freedom.",
        adaptations: "none",
        cover: "/images/forest.jfif",
    },
    {
        name: "Foundation",
        author: "Isaac Asimov",
        year: 1951,
        synopsis: "Foundation is the first book in Isaac Asimov's Foundation series. It revolves around the concept of 'psychohistory', a mathematical science that predicts the future of large populations. The story follows Hari Seldon, who predicts the fall of the Galactic Empire and works to establish a foundation to reduce the ensuing dark age.",
        adaptations: "Foundation (AppleTv+ series) - 2021",
        cover: "/images/foundation.jpg",
    },
    {
        name: "Roadside Picnic",
        author: "Arkady and Boris Strugatsky",
        year: 1972,
        synopsis: "Roadside Picnic is a Soviet science fiction novel that takes place in a mysterious, dangerous zone where extraterrestrial artifacts have been left behind. The story follows a 'stalker' who ventures into the zone to recover these strange objects.",
        adaptations: "Stalker (movie) - 1979",
        cover: "/images/roadside.jpg",
    },
    {
        name: "The Hitchhiker's Guide to the Galaxy",
        author: "Douglas Adams",
        year: 1979,
        synopsis: "This humorous and absurd science fiction series begins with the accidental hero, Arthur Dent, who is saved from the destruction of Earth by Ford Prefect, an alien writer for the titular guidebook. The story follows their intergalactic adventures and the bizarre characters they encounter.",
        adaptations: "The Hitchhiker's Guide to the Galaxy (BBC series) - 1981 / The Hitchhiker's Guide to the Galaxy (movie) - 2005",
        cover: "/images/hitchhikers.jpg",
    },
    {
        name: "Kindred",
        author: "Octavia E. Butler",
        year: 1979,
        synopsis: "Kindred is a time-travel novel that follows the journey of Dana, a modern Black woman who is inexplicably transported back in time to the antebellum South. She must confront the challenges and brutal realities of slavery while trying to survive and make sense of her situation.",
        adaptations: "Kindred (FX-Hulu series) - 2022",
        cover: "/images/kindred.jpg",
    },
    {
        name: "1984",
        author: "George Orwell",
        year: 1949,
        synopsis: "George Orwell's dystopian masterpiece is set in a totalitarian society under the constant surveillance of Big Brother. It follows the story of Winston Smith, who rebels against the oppressive regime and falls in love with Julia, leading to dire consequences.",
        adaptations: "1984 (movie) - 1956 / 1984 (movie) - 1984",
        cover: "/images/1984.jpg",
    },
    {
        name: "Flowers for Algernon",
        author: "Daniel Keyes",
        year: 1966,
        synopsis: "This touching novel is written as a series of progress reports by Charlie Gordon, a man with intellectual disabilities who undergoes an experimental procedure to increase his intelligence. The book explores themes of intelligence, empathy, and the human condition.",
        adaptations: "Charly (movie) - 1968",
        cover: "/images/algernon.jpg",
    },
    {
        name: "The Fifth Season",
        author: "N. K. Jemisin",
        year: 2015,
        synopsis: "This is the first book in 'The Broken Earth' trilogy. In a world prone to devastating geological catastrophes, individuals known as orogenes have the power to control and mitigate these events. The story follows three women with this ability and explores themes of power, oppression, and survival.",
        cover: "/images/thefifthseason.jpg",
    },
    {
        name: "Do Androids Dream of Electric Sheep?",
        author: "Philip K. Dick",
        year: 1968,
        synopsis: "Set in a post-apocalyptic future, this novel explores the moral and philosophical questions surrounding artificial intelligence and humanity. It follows the story of Rick Deckard, a bounty hunter tasked with 'retiring' rogue androids.",
        adaptations: "Blade Runner (movie) - 1982",
        cover: "/images/androids.jpg",
    },
];

export { collection };